### PR TITLE
Fix FTBFS on gcc 13

### PR DESCRIPTION
**Pull request by tserong**
This applies the following two patches:

- https://github.com/facebook/rocksdb/pull/11118
- https://github.com/facebook/rocksdb/pull/11137

See https://github.com/ceph/ceph/pull/50438 for further discussion.

### CODE REVIEW

**Comment by tserong** [comment]
I don't think that format check is failing on the code introduced in this PR, so can I assume we ignore that?

**Comment by tserong** [comment]
ping @cbodley @rzarzynski :-)

**Comment by cbodley** [comment]
bump!

**Review by rzarzynski — APPROVED** [review]
CC: @markhpc, @aclamk.

**Comment by rzarzynski** [comment]
For Reef this should be fine assuming we'll stick to the new RocksDB version.
For Quincy a PR targeting separated branch would be needed.

**Comment by cbodley** [comment]
@rzarzynski @markhpc @aclamk any objections to merging this so we can unblock https://github.com/ceph/ceph/pull/50438?

**Review by markhpc — APPROVED** [review]
LGTM

**Comment by cbodley** [comment]
there's a failing check that complains about code formatting. should this be a blocker, or can we go ahead and merge? afaik, the commits were taken directly from upstream rocksdb

**Comment by tserong** [comment]
Yeah this was just lifted from upstream, also AFAICT the format check is failing on code unrelated to this PR

**Comment by cbodley** [comment]
i would love to see this merge so i can build ceph on fedora 38

**Comment by rzarzynski** [comment]
@cbodley: merging this, so it should be possible to update the submodule in `ceph/ceph.git`.

**Comment by cbodley** [comment]
thanks @rzarzynski! would you like me to update the submodule?

**Comment by rzarzynski** [comment]
Feel free to bump it up, @cbodley! I can send a PR if you prefer.

**Comment by cbodley** [comment]
see https://github.com/ceph/ceph/pull/51737

**Pull request merged**
