### PR TITLE
rocksdb: Fix for http://tracker.ceph.com/issues/20529

### PR DESCRIPTION
**Pull request by oliveiradan**
As mentioned before, in order to avoid some other "sse4.2" issues, it would be good to build it by default with "sse3", and test it at runtime if it supports "sse4.2". 

Signed-off-by: Daniel Oliveira <doliveira@suse.com>

### CODE REVIEW

**Comment by mikaelfrykholm** [comment]
Maybe this should be renamed to "Bluestore broken on non sse4.2 hardware" ?

**Comment by oliveiradan** [comment]
Humm, well not really sure we want to change it from the standard; [module/submodule] we use, but the description does make sense. Will discuss that with upstream. It probably would be better to build it with '-msse3' by default and only check/enable specific API's if/when needed and supported by the CPU.

**Comment by aderumier** [comment]
Hi, we need to remove too  this:

`--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -813,11 +813,7 @@ if (NOT WITH_SYSTEM_ROCKSDB)
 
   # We really want to have the CRC32 calculation in RocksDB accelerated
   # with SSE 4.2. For details refer to rocksdb/util/crc32c.cc.
-  if (HAVE_INTEL_SSE4_2)
-    list(APPEND ROCKSDB_CMAKE_ARGS -DCMAKE_CXX_FLAGS=${SIMD_COMPILE_FLAGS})
-  else()
-    list(APPEND ROCKSDB_CMAKE_ARGS -DWITH_SSE42=OFF)
-  endif()
+  list(APPEND ROCKSDB_CMAKE_ARGS -DWITH_SSE42=OFF)
`

or msee4.2 is also in SIMD_COMPILE_FLAGS}.

Not sure that we need msse3. (amd opteron processors don't support them).

cockroach had the same problem with crc32, and have also patched util/crc32c.cc to get sse4.2 enabled at runtime
https://github.com/benesch/cockroach/commit/47ccc407fbaf61d9c95d36112b9af38625e90914

**Comment by aderumier** [comment]
I have tried to build debian package with your rocksdb patch, but it's failing.

I have tried with 
cockroachdb/rocksdb@87c3949
and it's working fine.

I have done benchmark with perf record, and I'm seeing rocksdb6crc32..Fast_... for my xeon v3, and   rocksdb6crc32..Slow_...  for my old xeon.

**Comment by oliveiradan** [comment]
@aderumier , Interesting it's failing. I was able to build it here with no problems. I wonder if that is due to an old/older compiler?! 

Also, the problem with: 
```
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -813,11 +813,7 @@ if (NOT WITH_SYSTEM_ROCKSDB)
 
   # We really want to have the CRC32 calculation in RocksDB accelerated
   # with SSE 4.2. For details refer to rocksdb/util/crc32c.cc.
-  if (HAVE_INTEL_SSE4_2)
-    list(APPEND ROCKSDB_CMAKE_ARGS -DCMAKE_CXX_FLAGS=${SIMD_COMPILE_FLAGS})
-  else()
-    list(APPEND ROCKSDB_CMAKE_ARGS -DWITH_SSE42=OFF)
-  endif()
+  list(APPEND ROCKSDB_CMAKE_ARGS -DWITH_SSE42=OFF)
```
Is that we are checking (again) on SSE42 during the build time. What if we build it on a machine that supports the feature in question and then we get the binaries over to a machine that won't support it?
Which is the problem we are facing and the reason why when we have a build on a machine that does not support SSE42 these CMakeLists.txt are checked and *no SSE42 are passing in,* then things all work fine.

**Comment by aderumier** [comment]
>>@aderumier , Interesting it's failing. I was able to build it here with no problems. I wonder if that is due to >>an old/older compiler?!
I think it's work with I build with cmake manually, but fail when building deb package with dpkg-buildpackage. I'll retest to be sure.

>>Is that we are checking (again) on SSE42 during the build time. What if we build it on a machine that >>supports the feature in question and then we get the binaries over to a machine that won't support it?
yes, if we build sse42 support on a recent cpu, it'll not work on older xeon.
That's why it need to be enabled on runtime.

>>Which is the problem we are facing and the reason why when we have a build on a machine that does >>not support SSE42 these CMakeLists.txt are checked and no SSE42 is passed in, then things all work >>fine.

I think it's more complicated, because building package on my old xeon, don't work too. I think the sse42 detection is not working correctly, and the flag is always enabled at build time, even if the processor don't support it.

**Comment by aderumier** [comment]
here the output with your patch

cmake ../ -DUSE_CRYPTOPP=OFF -DWITH_OCF=ON -DWITH_LTTNG=ON -DWITH_PYTHON3=ON -DWITH_EMBEDDED=OFF  -DWITH_CEPHFS_JAVA=ON  -DCMAKE_INSTALL_LIBDIR=/usr/lib -DCMAKE_INSTALL_LIBEXECDIR=/usr/lib -DCMAKE_INSTALL_SYSCONFDIR=/etc
 
``
In file included from /usr/lib/gcc/x86_64-linux-gnu/6/include/nmmintrin.h:31:0,
                 from /var/lib/vz/proxmox2/ceph/src/rocksdb/util/crc32c.cc:20:
/usr/lib/gcc/x86_64-linux-gnu/6/include/smmintrin.h: In function ‘void rocksdb::crc32c::Fast_CRC32(uint64_t*, const uint8_t**)’:
/usr/lib/gcc/x86_64-linux-gnu/6/include/smmintrin.h:846:1: error: inlining failed in call to always_inline ‘long long unsigned int _mm_crc32_u64(long long unsigned int, long long unsigned int)’: target specific option mismatch
 _mm_crc32_u64 (unsigned long long __C, unsigned long long __V)
 ^~~~~~~~~~~~~
/var/lib/vz/proxmox2/ceph/src/rocksdb/util/crc32c.cc:456:25: note: called from here
       *l = _mm_crc32_u64(*l, LE_LOAD64(*p));
            ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
In file included from /usr/lib/gcc/x86_64-linux-gnu/6/include/nmmintrin.h:31:0,
                 from /var/lib/vz/proxmox2/ceph/src/rocksdb/util/crc32c.cc:20:
/usr/lib/gcc/x86_64-linux-gnu/6/include/smmintrin.h:846:1: error: inlining failed in call to always_inline ‘long long unsigned int _mm_crc32_u64(long long unsigned int, long long unsigned int)’: target specific option mismatch
 _mm_crc32_u64 (unsigned long long __C, unsigned long long __V)
 ^~~~~~~~~~~~~
/var/lib/vz/proxmox2/ceph/src/rocksdb/util/crc32c.cc:456:25: note: called from here
       *l = _mm_crc32_u64(*l, LE_LOAD64(*p));
            ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
In file included from /usr/lib/gcc/x86_64-linux-gnu/6/include/nmmintrin.h:31:0,
                 from /var/lib/vz/proxmox2/ceph/src/rocksdb/util/crc32c.cc:20:
/usr/lib/gcc/x86_64-linux-gnu/6/include/smmintrin.h:846:1: error: inlining failed in call to always_inline ‘long long unsigned int _mm_crc32_u64(long long unsigned int, long long unsigned int)’: target specific option mismatch
 _mm_crc32_u64 (unsigned long long __C, unsigned long long __V)
 ^~~~~~~~~~~~~
/var/lib/vz/proxmox2/ceph/src/rocksdb/util/crc32c.cc:456:25: note: called from here
       *l = _mm_crc32_u64(*l, LE_LOAD64(*p));
            ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
CMakeFiles/rocksdb.dir/build.make:3038 : la recette pour la cible « CMakeFiles/rocksdb.dir/util/crc32c.cc.o » a échouée
``

**Comment by aderumier** [comment]
oh sorry, I dind't see that you have merged last rocksdb master in your branch, maybe that's why I can't compile your patch. I'll retry.

**Comment by oliveiradan** [comment]
1. Some of these intrinsics (_mm_crc32_u64 included) are 'sse4' specific (https://software.intel.com/sites/landingpage/IntrinsicsGuide/#techs=SSE3,SSSE3,SSE4_1,SSE4_2), which could be causing the issue when building it (when tried from a machine that doesn't support it). 
2. Yes, we are not using the very latest rocksdb master, so there is *some hacking* needed when the patch gets accepted upstream (ceph/rocksdb).

**Pull request closed without merging**
