### PR TITLE
rocksdb:Fixes for http://tracker.ceph.com/issues/20529

### PR DESCRIPTION
**Pull request by oliveiradan**
This is fix for bug #20529 http://tracker.ceph.com/issues/20529 . No CMakeLists.txt changed, but it would be good to build with '-msse3' by default, instead of '-msse4.2'.

### CODE REVIEW

**Comment by oliveiradan** [comment]
I don't have anything upstream for Facebook/rocksdb. I forked Ceph/rocksdb and submitted changes based on that on.
		
		

		Get Outlook for iOS
	




On Sat, Aug 5, 2017 at 2:32 AM -0600, "Jos Collin" <notifications@github.com> wrote:












@joscollin requested changes on this pull request.



ceph/rocksdb is a fork of facebook/rocksdb. Do you have an upstream fix that was already merged in facebook/rocksdb ?

**Comment by oliveiradan** [comment]
However, if there is anything as far as building Facebook/rocksdb with -msse3 and a fix the problem in question, I am all for it. Just not sure how/why we didn't pull it. 
		
		

		Get Outlook for iOS
	




On Sun, Aug 6, 2017 at 3:56 PM -0600, <doliveirabrz@gmail.com> wrote:













	
		
		
	
		I don't have anything upstream for Facebook/rocksdb. I forked Ceph/rocksdb and submitted changes based on that on.
		
		

		Get Outlook for iOS
	




On Sat, Aug 5, 2017 at 2:32 AM -0600, "Jos Collin" <notifications@github.com> wrote:












@joscollin requested changes on this pull request.



ceph/rocksdb is a fork of facebook/rocksdb. Do you have an upstream fix that was already merged in facebook/rocksdb ?

**Comment by liewegas** [comment]
I don't understand why this fixes the Illegal instruction segv.  Even with the current code the call to ExtendImpl<Fast_CRC32> is guarded by IsSSE42(), right?

**Comment by oliveiradan** [comment]
@liewegas, 

I am not sure anything has happened in facebook/rocksdb upstream. I didn't really check for it there (my fork was/is based on ceph/rocksdb as you pointed me to last Friday) and my assumption was that anything that was already fixed in facebook/rocksdb upstream would be fixed/pulled into our ceph/rocksdb, so if we are/were facing a problem with out branch then most likely they would too and/or we didn't have a fix for it in our branch. 

Now, we are compiling rocksdb with '-msse4.2' across the board. My understanding is that the CRC32C code for checksum is the only place in which the hardware CRC32C could really have some gain by using SSE4.2 instructions. 

My suggestion on #1 comment (and that was the thing I didn't touch expecting we could talk/discuss the best way/place for us to do it [../build_tools/build_detect_platform/, CMakeLists.txt, buckifier/targets_cfg.py...]) is that we could build it with '-msse3' so most of the older CPUs should be ok/covered and only pieces/parts we really needed with '-msse4.2'. 

Regarding to your question 'Even with the current code the call to ExtendImpl<Fast_CRC32> is guarded by IsSSE42(), right?' . 

If we are building it with '-msse4.2' and forcing it to be built with -DHAVE_SSE42 (so most likely setting it to use USE_SSE=1 when building it), I don't think the 'guard' would work as expected, otherwise we would not be facing this issue (it should be able to fallback to the slow CRC32 code [not SSE42]), besides the fact some of those checkings are only at compile time (HAVE_SSE42 / __SSE4_2__ , based checks). 

I ended up re-writing a few things and also, got the part of the code I was missing during the push (probably I got a different file or branch), where we can check now for the cpu feature in question like: 
```if (!is_cpu_feature_available(CpuSSEFeature::SSE4_2)){ 
do_stuff...
```
I got it all rebuilding now (2am Mountain), before I push it again.

**Pull request closed without merging**
