### PR TITLE
[win32] allow using posix threads

### PR DESCRIPTION
**Pull request by petrutlucian94**
Allow building Rocksdb using mingw and Posix threads.

Rocksdb is using the c++11 std::threads feature. The issue is that MINGW only supports it when using Posix threads.

This change will allow rocksdb::port::WindowsThread to be replaced with std::thread, which in turn will allow Rocksdb to be cross compiled using MINGW.

At the same time, we'll have to use GetCurrentProcessId instead of _getpid.

Signed-off-by: Lucian Petrut <lpetrut@cloudbasesolutions.com>

### CODE REVIEW

**Comment by ml8mr** [comment]
These changes worked in my environment.

**Comment by tchaikov** [comment]
@petrutlucian94 could you upstream this change to https://github.com/facebook/rocksdb ? we will pick up a commit or better off an upstream release with your change once it gets merged.

**Comment by petrutlucian94** [comment]
> @petrutlucian94 could you upstream this change to https://github.com/facebook/rocksdb ? we will pick up a commit or better off an upstream release with your change once it gets merged.

Makes sense, sure.

**Comment by petrutlucian94** [comment]
Closing this for now in favor of the upstream PR.

**Comment by petrutlucian94** [comment]
The upstream PR has merged: https://github.com/facebook/rocksdb/pull/6865

**Comment by tchaikov** [comment]
@petrutlucian94 hi Lucian, thanks for pushing this change to upstream. i forgot to ask, why do you want to build rocksdb for getting the ceph client side on MinGW?

**Comment by petrutlucian94** [comment]
Some of the Ceph tools were using it and since it was trivial to cover, we went for it. Also, we're storing some data about persistent rbd mappings and plan to do the same for cephfs mounts. We're currently storing this data in the Windows registry but if we were to use a portable approach across platforms, rocksdb might be a good choice.

Depending on the feedback we get, we might consider at least trying to run OSDs on Windows as well in the not so distant future.

**Comment by tchaikov** [comment]
@petrutlucian94 thanks for the detailed explanation! that's an ambitious project to port OSD to windows!

**Comment by tchaikov** [comment]
let me know once you need this change in ceph. normally, we try to pick up a stable release of rocksdb, but if this is a blocker for you. we can reevaluate and see if we need to make an exception.

**Comment by petrutlucian94** [comment]
> let me know once you need this change in ceph. normally, we try to pick up a stable release of rocksdb, but if this is a blocker for you. we can reevaluate and see if we need to make an exception.

Thanks! They seem to release quite often, so we should be ok waiting for a stable release.

**Pull request closed without merging**
