### PR TITLE
cmake: check -momit-leaf-frame-pointer before using it

### PR DESCRIPTION
**Pull request by tchaikov**

### CODE REVIEW

**Comment by tchaikov** [comment]
@smithfarm these changes are pending on review from upstream. maybe we can have them before the merge?

**Comment by smithfarm** [comment]
The first commit is https://github.com/facebook/rocksdb/pull/1762 and the second is https://github.com/facebook/rocksdb/pull/1757

**Comment by smithfarm** [comment]
@tchaikov Given that these are cherry-picks, could you use `-x` ?

**Comment by tchaikov** [comment]
> The first commit is facebook#1762 and the second is facebook#1757

yeah!

> Given that these are cherry-picks, could you use `-x` ?

@smithfarm the sha1 of them will change after the merge, so i think it won't make sense to add the "cherry picked from commit" lines *before* the upstream merge.

**Comment by smithfarm** [comment]
@tchaikov I don't think merging a PR changes the sha1 - I guess I'm missing something.

**Comment by smithfarm** [comment]
But I agree that it's not a good idea to cite the sha1 until after the upstream merge, since the upstream PR might need to be rebased.

**Comment by smithfarm** [comment]
In any case, thanks for the fix - I will test it and post the result here.

**Comment by tchaikov** [comment]
>  since the upstream PR might need to be rebased.

yeah, that's what i meant.

@smithfarm thanks!

**Comment by smithfarm** [comment]
@tchaikov Could you push this wip branch to ceph/rocksdb.git please?

**Comment by tchaikov** [comment]
https://github.com/ceph/ceph/pull/12908

**Pull request closed without merging**
